"""Shared settings for the Zoodle project."""

from .settings import (
    ANIMAL_CLASSES,
    ANIMAL_GROUPS,
    DATASET_URL,
    EDA_OUTPUT_DIR,
    IMAGE_SIZE,
    PCA_OUTPUT_DIR,
    PCA_SAMPLES_PER_CLASS,
    PCA_VARIANCE,
    PROCESSED_DATA_DIR,
    RANDOM_STATE,
    RAW_DATA_DIR,
    SAMPLES_PER_CLASS,
    TEST_RATIO,
    TRAIN_RATIO,
    UMAP_MIN_DIST,
    UMAP_N_NEIGHBORS,
    UMAP_OUTPUT_DIR,
    UMAP_SAMPLES_PER_CLASS,
    VALIDATION_RATIO,
)
